sudo: required
language: generic 
services:
  - docker

before_install:
  - docker build -t bandzior-git/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true bandzior-git/react-test npm test

after_success:
  - docker build -t bandzior-git/multi-client ./client
  - docker build -t bandzior-git/multi-nginx ./nginx
  - docker build -t bandzior-git/multi-server ./server
  - docker build -t bandzior-git/multi-worker ./worker
  # Login to docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Push images to docker hub
  - docker push bandzior/multi-client
  - docker push bandzior/multi-nginx
  - docker push bandzior/multi-server
  - docker push bandzior/multi-worker
