sudo: required
language: generic 
services:
  - docker

before_install:
  - docker build -t bandzior-git/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true bandzior-git/react-test npm test

after_success:
  - docker build -t bandzior-git/multi-client ./client
  - docker build -t bandzior-git/multi-nginx ./nginx
  - docker build -t bandzior-git/multi-server ./server
  - docker build -t bandzior-git/multi-worker ./worker

# Login to docker CLI